


default_platform(:android)

platform :android do
  desc "Lane for android firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --split-per-abi"
    firebase_app_distribution(
      app:"1:639566722587:android:e654ceab6f7232bb1d2abe",
      firebase_cli_token:ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type:"APK",
      android_artifact_path:"../build/app/outputs/flutter-apk/app-arm64-v8a-release.apk",
      groups:"sehha_link_testers",
      release_notes:"First Fastlane Firebase Distribution for Attendo"
    )
  end
end